{% set name = "hatch-cpp" %}
{% set version = "0.3.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/hatch-cpp/hatch_cpp-{{ version }}.tar.gz
  sha256: b2178ca8110fb86b26cb3f64b78ff61ffdabf1aaf8fb8b18480a90e684f064b4

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.20
  run:
    - python >={{ python_min }}
    - hatchling >=1.20
    - hatch-build >=0.5,<0.6
    - pydantic

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - hatch_cpp

about:
  home: https://github.com/python-project-templates/hatch-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Hatch plugin for C++ builds
  description: Hatch plugin for C++ builds
  dev_url: https://github.com/python-project-templates/hatch-cpp

extra:
  recipe-maintainers:
    - timkpaine
