{% set name = "hatch-cpp" %}
{% set version = "0.1.5" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/hatch-cpp/hatch_cpp-{{ version }}.tar.gz
  sha256: 8e81296cb838aa436f5e6edcacec6d73b8f8108ada5f07cc144b5ae9b7e76251

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.20
  run:
    - python >={{ python_min }}
    - hatchling >=1.20
    - pydantic >=2

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - hatch_cpp

about:
  home: https://github.com/python-project-templates/hatch-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Hatch plugin for C++ builds
  description: Hatch plugin for C++ builds
  dev_url: https://github.com/python-project-templates/hatch-cpp

extra:
  recipe-maintainers:
    - timkpaine
