{% set name = "hatch-cpp" %}
{% set version = "0.2.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/hatch-cpp/hatch_cpp-{{ version }}.tar.gz
  sha256: 9d40f8dc8520d29c260eba5617857bf76de1d832bd7137a0cc53c058f8d0f0da

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.20
  run:
    - python >={{ python_min }}
    - hatchling >=1.20
    - pydantic >=2

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - hatch_cpp

about:
  home: https://github.com/python-project-templates/hatch-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Hatch plugin for C++ builds
  description: Hatch plugin for C++ builds
  dev_url: https://github.com/python-project-templates/hatch-cpp

extra:
  recipe-maintainers:
    - timkpaine
